In [2]:
import numpy as np

In [2]:
# to see the list of installed libraries
# pip list

In [3]:
l1 = [1,2,3,4,5,6]
print(type(l1))
print(l1)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [4]:
l1_arr = np.array(l1)
print(type(l1_arr))
print(l1_arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [5]:
a1 = np.array([1,2,3,4])
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[1 2 3 4]


In [6]:
a1

array([1, 2, 3, 4])

In [7]:
l1_arr


array([1, 2, 3, 4, 5, 6])

In [8]:
# addition of elemnts of an array - sum()
sumarr = l1_arr.sum()
print(sumarr)

21


In [9]:
# chcek item size
print(l1_arr.itemsize)

4


In [10]:
# data type of array
print(l1_arr.dtype)

int32


In [11]:
# check array dimension 
print(l1_arr.ndim)

1


In [12]:
# array shape
print(l1_arr.shape)

(6,)


In [13]:
l1_arr

array([1, 2, 3, 4, 5, 6])

In [14]:
l2 = l1_arr.reshape(3,2)
l2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
l3 = l1_arr.reshape(2,3)
l3

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
l2.ndim

2

In [17]:
l3.ndim

2

In [18]:
l1_arr

array([1, 2, 3, 4, 5, 6])

In [19]:
np.sum(l1_arr)

21

In [20]:
np.mean(l1_arr)

3.5

In [21]:
np.median(l1_arr)

3.5

In [22]:
np.mean(l2)

3.5

In [35]:
l4 = [1,2,3,45,6,7,3,1,2,3,5,6,2,3,3,3]
arr = np.array(l4)
arr

array([ 1,  2,  3, 45,  6,  7,  3,  1,  2,  3,  5,  6,  2,  3,  3,  3])

In [24]:
np.sum(arr)

170

In [25]:
np.mean(arr)

14.166666666666666

In [26]:
np.median(arr)

4.0

In [27]:
from scipy import stats

In [36]:
arr

array([ 1,  2,  3, 45,  6,  7,  3,  1,  2,  3,  5,  6,  2,  3,  3,  3])

In [37]:
m = stats.mode(arr)
m

ModeResult(mode=array([3]), count=array([6]))

In [38]:
np.mean(arr)

5.9375

In [40]:
np.median(arr)

3.0

In [41]:
arr

array([ 1,  2,  3, 45,  6,  7,  3,  1,  2,  3,  5,  6,  2,  3,  3,  3])

In [50]:
#2D Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
type(a)

numpy.ndarray

In [52]:
a.ndim

2

In [53]:
a.shape

(3, 3)

In [54]:
m1 = np.array([[1,2],[3,4]])
m1

array([[1, 2],
       [3, 4]])

In [55]:
m2 = np.array([[5,6],[7,8]])
m2

array([[5, 6],
       [7, 8]])

In [56]:
m3 = m1 + m2
m3

array([[ 6,  8],
       [10, 12]])

In [57]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [58]:
# matrix defination
m1 = np.matrix([[1,2],[3,4]])
m1

matrix([[1, 2],
        [3, 4]])

In [59]:
m2 = np.matrix([[5,6],[7,8]])
m2

matrix([[5, 6],
        [7, 8]])

In [64]:
m3 = m1 * m2
m3

matrix([[19, 22],
        [43, 50]])

In [65]:
m4 = m1 + m2
m4

matrix([[ 6,  8],
        [10, 12]])

In [66]:
type(m3)

numpy.matrix

In [67]:
type(m4)

numpy.matrix

In [69]:
# create array with zeros
b = np.zeros(3)
b

array([0., 0., 0.])

In [70]:
type(b)

numpy.ndarray

In [71]:
b.ndim

1

In [72]:
b.shape

(3,)

In [74]:
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [77]:
# identity matrix
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
n = np.full((2,2),4)
n

array([[4, 4],
       [4, 4]])

In [80]:
arr = np.arange(5,25)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [81]:
type(arr)

numpy.ndarray

In [83]:
x = arr.reshape(5,4)
x

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [85]:
y = x.flatten()
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [86]:
type(m1)

numpy.matrix

In [88]:
m1

matrix([[1, 2],
        [3, 4]])

In [87]:
m1.transpose()

matrix([[1, 3],
        [2, 4]])

In [90]:
x

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [89]:
x.transpose()

array([[ 5,  9, 13, 17, 21],
       [ 6, 10, 14, 18, 22],
       [ 7, 11, 15, 19, 23],
       [ 8, 12, 16, 20, 24]])

In [91]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [92]:
a

array([1, 2, 3])

In [93]:
b

array([4, 5, 6])

In [97]:
c = np.concatenate((a,b), axis = 0)
c

array([1, 2, 3, 4, 5, 6])

In [99]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,22,33],[44,55,66]])

In [100]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [102]:
c = np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [104]:
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [106]:
# slicing

In [119]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [120]:
a[:1]

array([[1, 2, 3, 4]])

In [121]:
a[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [122]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
a[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [125]:
a[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
a[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [128]:
a[:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [129]:
a[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [132]:
a[2:,:2]

array([[ 9, 10],
       [13, 14]])

In [133]:
a[2:,2:]

array([[11, 12],
       [15, 16]])

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# start, end, incr/decr
arr[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[::2]

array([1, 3, 5, 7, 9])

In [8]:
arr[-1]

9

In [10]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[3:7]

array([4, 5, 6, 7])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#arr[row, col]
#arr[s:e:i/d,s:e:i/d]
arr[1:]

array([[4, 5, 6]])

In [23]:
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr[::1]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr[::2]

array([[1, 2, 3]])

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr[::,1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr[::,:2]

array([[1, 2],
       [4, 5]])

In [30]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr[:,::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
arr[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
arr[:,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [5]:
arr[2:,:3]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [6]:
arr[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [9]:
arr[:3,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
arr[::-1,::-1]

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [13]:
arr[::-1]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [14]:
arr[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [30]:
arr = np.array([11,3,56,34,89,2,9,5,46])
arr

array([11,  3, 56, 34, 89,  2,  9,  5, 46])

In [31]:
np.sum(arr)

255

In [23]:
np.max(arr)

89

In [24]:
np.min(arr)

2

In [25]:
arr

array([11,  3, 56, 34, 89,  2,  9,  5, 46])

In [26]:
# display all odd numbers
arr[arr%2==1]

array([11,  3, 89,  9,  5])

In [27]:
# display all even numbers
arr[arr%2==0]

array([56, 34,  2, 46])

In [29]:
# replace all even numbers with 0
arr[arr%2==0] = 0
arr

array([11,  3,  0,  0, 89,  0,  9,  5,  0])

In [32]:
arr

array([11,  3, 56, 34, 89,  2,  9,  5, 46])

In [33]:
arr[2]

56

In [34]:
arr[2] = 76

In [35]:
arr

array([11,  3, 76, 34, 89,  2,  9,  5, 46])

In [36]:
# array iterating - 1D Array
for x in arr:
    print(x)

11
3
76
34
89
2
9
5
46


In [37]:
arr1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
# Iterate 2D array
for x in arr1:
    print(x)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [40]:
# Iterate 2D array
for x  in arr1:
    for y in x:
        print(y, end= ' ')
    print()

1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 


In [41]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

np.concatenate((a1, a2))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
np.concatenate((a1, a2), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
a3 = np.array([[1,2],[3,4]])
a4 = np.array([[5,6],[7,8]])

In [46]:
a3

array([[1, 2],
       [3, 4]])

In [47]:
a4

array([[5, 6],
       [7, 8]])

In [48]:
np.concatenate((a3,a4))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.concatenate((a3,a4), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
np.concatenate((a3,a4), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
arr

array([11,  3, 76, 34, 89,  2,  9,  5, 46])

In [52]:
np.array_split(arr,2)

[array([11,  3, 76, 34, 89]), array([ 2,  9,  5, 46])]

In [53]:
np.array_split(arr,3)

[array([11,  3, 76]), array([34, 89,  2]), array([ 9,  5, 46])]

In [54]:
np.array_split(arr,4)

[array([11,  3, 76]), array([34, 89]), array([2, 9]), array([ 5, 46])]

In [55]:
np.array_split(arr,5)

[array([11,  3]), array([76, 34]), array([89,  2]), array([9, 5]), array([46])]

In [56]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
np.array_split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [58]:
np.array_split(arr,3)

[array([11,  3, 76]), array([34, 89,  2]), array([ 9,  5, 46])]

In [59]:
np.array_split(arr1,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [60]:
np.array_split(arr1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [61]:
np.array_split(arr1,5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([], shape=(0, 4), dtype=int32)]

In [2]:
#search - returns an index
arr = np.array([1,2,3,4,5,6])

np.where(arr == 5)

(array([4], dtype=int64),)

In [4]:
x = np.where(arr == 9)
x

(array([], dtype=int64),)

In [5]:
np.where(arr%2==0)

(array([1, 3, 5], dtype=int64),)

In [8]:
arr1 = np.array([12, 56,89,32,75, 37, 63])

In [9]:
np.where(arr1%2!=0)

(array([2, 4, 5, 6], dtype=int64),)

In [17]:
arr2 = np.array([1,2,3,4,5,6])
arr2.shape

(6,)

In [21]:
x = np.searchsorted(arr2, 4)
x

3

In [22]:
np.searchsorted(arr2, 9)

6

In [23]:
np.searchsorted(arr2, 2)

1

In [27]:
np.searchsorted(arr2, 5)

4

In [56]:
arr3 = np.array([15, 36,49, 57, 66, 88])
arr3.shape

(6,)

In [59]:
np.searchsorted(arr3, 24)

1

In [64]:
arr = np.array([23,55,14,6,89,34,-2])

In [65]:
np.sort(arr)

array([-2,  6, 14, 23, 34, 55, 89])

In [66]:
data = np.array(['Raj', 'Arya', 'Megh', 'Neha'])

In [67]:
np.sort(data)

array(['Arya', 'Megh', 'Neha', 'Raj'], dtype='<U4')

In [74]:
a = np.array([[13,-2,7], [11,4,9]])
a

array([[13, -2,  7],
       [11,  4,  9]])

In [75]:
np.sort(a)

array([[-2,  7, 13],
       [ 4,  9, 11]])

In [79]:
np.sort(a,axis=1, kind='quicksort')    #sort array row wise

array([[-2,  7, 13],
       [ 4,  9, 11]])

In [77]:
a

array([[13, -2,  7],
       [11,  4,  9]])

In [78]:
np.sort(a,axis=0)      #sort array column wise 

array([[11, -2,  7],
       [13,  4,  9]])

In [80]:
# Filtering
arr = np.array([23,56,89,101])
x = [True, False,False,True]

In [81]:
type(x)

list

In [82]:
type(arr)

numpy.ndarray

In [83]:
arr1 = arr[x]
arr1

array([ 23, 101])

In [87]:
# create a filter array which return a value > num. Accept value of num from user
data = np.array([34,156, 56, -2,13,88,32, 23, 78])
num = int(input('Enter number : '))
farr_list = []
for x in data:
    if(x > num):
        farr_list.append(True)
    else:
        farr_list.append(False)
        
        
print(type(farr_list))
print(farr_list)

arr1 = data[farr_list]
print(arr1)

Enter number :  75


<class 'list'>
[False, True, False, False, False, True, False, False, True]
[156  88  78]


In [89]:
data = np.array([34,156, 56, -2,13,88,32, 23, 78])
num = int(input('Enter number : '))
farr_list = data > num
          
print(farr_list)

arr1 = data[farr_list]
print(arr1)

Enter number :  60


[False  True False False False  True False False  True]
[156  88  78]


In [91]:
data = np.array([34,156, 56, -2,13,88,32, 23, 78])

farr_list = data%2==1
          
print(farr_list)

arr1 = data[farr_list]
print(arr1)

[False False False False  True False False  True False]
[13 23]


In [92]:
from numpy import random

In [102]:
# generate random int within given range
x = random.randint(1000)
x

208

In [111]:
# generate n float numbers
x = random.rand(4)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0.80355814 0.12585404 0.3302764  0.68882631]


In [115]:
# generate 1D array
x = random.randint(100, size=(5))
print(type(x))
print(x)

<class 'numpy.ndarray'>
[67 48  2 80 54]


In [116]:
# generate 2D array
x = random.randint(100, size=(3,3))
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[95 77 30]
 [23 89 21]
 [91 50 87]]


### Create a 3x3x3 array with random values

In [119]:
x = random.randint(100, size=(3,3,3))
x

array([[[55, 67,  0],
        [80, 76, 36],
        [90, 23, 76]],

       [[27, 70, 15],
        [34, 73, 10],
        [16, 15, 15]],

       [[59, 70, 58],
        [ 1, 52, 94],
        [83, 23, 17]]])

### Create a 10x10 array with random values and find the minimum and maximum 

In [121]:
x = random.randint(1500, size=(10,10))
print(x)
print('minimum : ', x.min())
print('maximum : ', x.max())

[[  33  921  664  692  975  768  876  226  261  145]
 [ 644  468  618  832 1310   95  307  813 1094  875]
 [1376 1374  714 1195  953  764  418   23 1493  629]
 [ 123  373  834 1382  574  464  511  564   69 1006]
 [  67  989   43  213  325  925 1398  421 1366  671]
 [1028  382   63  980  381  745  334  699 1021 1310]
 [1181 1102  128  250 1336 1094  866  855  490  499]
 [ 957 1366  904  588 1294  916  623   12  502   44]
 [ 147  157  574  292  754 1025  149 1419 1450  773]
 [ 435 1141 1092  279  562 1124  800  907  788  283]]
minimum :  12
maximum :  1493


### Create a random vector of size 20 and find the mean value

In [125]:
x = random.random(20)
print(x)
print(np.mean(x))

[0.31580929 0.99808296 0.90013005 0.7773106  0.00114668 0.51005793
 0.73687352 0.44453338 0.24555426 0.84053272 0.97134872 0.34691472
 0.1532684  0.819369   0.39518985 0.54550705 0.49678547 0.13693653
 0.85738775 0.0715251 ]
0.5282131991778936


In [145]:
# common elements between two arrays
n1 = random.randint(100, size=(10))
n2 = random.randint(100, size=(10))
print(n1)
print(n2)
print('intersection : ',np.intersect1d(n1,n2))
print('union : ',np.union1d(n1,n2))

[22 74 38 78 58 60 76 85 90 30]
[90 53 58 92 15  9 46  5 35 72]
intersection :  [58 90]
union :  [ 5  9 15 22 30 35 38 46 53 58 60 72 74 76 78 85 90 92]


In [146]:
n1 = random.randint(100, size=(3,3))
n2 = random.randint(100, size=(3,3))
print(n1)
print(n2)
print('intersection : ',np.intersect1d(n1,n2))
print('union : ',np.union1d(n1,n2))

[[93  0 71]
 [83  3 46]
 [ 4 29 48]]
[[42 42 87]
 [51  4  5]
 [44 40  5]]
intersection :  [4]
union :  [ 0  3  4  5 29 40 42 44 46 48 51 71 83 87 93]


### From array 'A' remove all items present in array 'B'

In [9]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array([1,2,3,8,9,6])
print(np.intersect1d(arr1, arr2))
print(np.setdiff1d(arr1,arr2))

[1 2 3]
[4 5]


### How to get the positions where elements of two arrays match?

In [6]:
a = np.array([1,12,3,4,5,6,7])
b = np.array([8,12,5,4,7,8,9])

x = np.where(a==b)
print (x)

(array([1, 3], dtype=int64),)


### How to swap two rows in a 2d numpy array?

### How to reverse the rows of a 2D array?

### How to reverse the columns of a 2D array?

### How to create a 2D array containing random floats 

### How to create a 2D array containing random floats between 10 and 20